#!/usr/bin/env python3
"""Surrogate-gradient BPTT training of an SNC-structured spiking net (Phase 5).

PyTorch drives data/optimizer/loss/logging; SNC provides the sparse topology
(generated by the C++ `snc_export` tool) and the spiking forward model. Example:

    python3 python/train.py --structure static-snc --hidden 256 \\
        --num-train 60000 --num-test 10000 --epochs 15 --device cuda
"""
import argparse
import os
import subprocess
import sys
import tempfile
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
import torch
import torch.nn.functional as F

import snc

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse():
    p = argparse.ArgumentParser()
    p.add_argument("--structure", default="static-snc",
                   choices=["dense", "random-sparse", "static-snc"])
    p.add_argument("--hidden", default="256", help="hidden width(s), e.g. 256 or 256,256")
    p.add_argument("--synapse-budget", type=int, default=40000)
    p.add_argument("--dataset", default="mnist")
    p.add_argument("--data-dir", default=os.path.join(ROOT, "data/mnist"))
    p.add_argument("--num-train", type=int, default=60000)
    p.add_argument("--num-test", type=int, default=10000)
    p.add_argument("--epochs", type=int, default=15)
    p.add_argument("--batch", type=int, default=128)
    p.add_argument("--num-steps", type=int, default=20)
    p.add_argument("--lr", type=float, default=2e-3)
    p.add_argument("--decay", type=float, default=0.9)
    p.add_argument("--threshold", type=float, default=1.0)
    p.add_argument("--gain", type=float, default=1.0)
    p.add_argument("--max-rate", type=float, default=0.5)
    p.add_argument("--w-init", type=float, default=0.1)
    p.add_argument("--surrogate-scale", type=float, default=10.0)
    p.add_argument("--encoder", default="poisson", choices=["poisson", "direct"])
    p.add_argument("--device", default="cuda")
    p.add_argument("--seed", type=int, default=1)
    p.add_argument("--export-bin", default=os.path.join(ROOT, "build/snc_export"))
    p.add_argument("--log-csv", default="")
    return p.parse_args()


def make_graph(a):
    layers = ",".join(["784"] + a.hidden.split(",") + ["10"])
    tmp = tempfile.NamedTemporaryFile(suffix=".bin", delete=False)
    tmp.close()
    cmd = [a.export_bin, "--structure", a.structure, "--layers", layers,
           "--synapse-budget", str(a.synapse_budget), "--seed", str(a.seed),
           "--out", tmp.name]
    out = subprocess.run(cmd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"snc_export failed:\n{out.stderr}")
    print(out.stdout.strip())
    return snc.load_graph(tmp.name)


def evaluate(model, X, y, batch, device):
    model.eval()
    correct = 0
    with torch.no_grad():
        for i in range(0, len(X), batch):
            xb = torch.from_numpy(X[i:i + batch]).to(device)
            logits = model(xb)
            correct += (logits.argmax(1).cpu().numpy() == y[i:i + batch]).sum()
    return correct / len(X)


def main():
    a = parse()
    torch.manual_seed(a.seed)
    np.random.seed(a.seed)
    device = a.device if (a.device != "cuda" or torch.cuda.is_available()) else "cpu"

    g = make_graph(a)
    Xtr, ytr, Xte, yte = snc.load_mnist(a.data_dir, a.num_train, a.num_test)
    model = snc.SNN(g, num_steps=a.num_steps, thr=a.threshold, decay=a.decay,
                    gain=a.gain, max_rate=a.max_rate, w_init=a.w_init,
                    surrogate_scale=a.surrogate_scale, encoder=a.encoder,
                    seed=a.seed).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=a.lr)
    n_params = sum(p.numel() for p in model.parameters())

    print(f"device={device} structure={a.structure} layers=784,{a.hidden},10 "
          f"synapses={n_params} steps={a.num_steps} batch={a.batch} lr={a.lr}")
    print(f"\nepoch  loss   train_acc  test_acc   sec")

    csv = open(a.log_csv, "w") if a.log_csv else None
    if csv:
        csv.write("epoch,loss,train_acc,test_acc\n")

    print(f"{0:5d}  {'-':>5}  {'-':>9}  {evaluate(model, Xte, yte, a.batch, device):.4f}")
    for e in range(1, a.epochs + 1):
        model.train()
        t0 = time.time()
        order = np.random.permutation(len(Xtr))
        loss_sum, correct = 0.0, 0
        for i in range(0, len(Xtr), a.batch):
            idx = order[i:i + a.batch]
            xb = torch.from_numpy(Xtr[idx]).to(device)
            yb = torch.from_numpy(ytr[idx]).to(device)
            opt.zero_grad()
            logits = model(xb)
            loss = F.cross_entropy(logits, yb)
            loss.backward()
            opt.step()
            loss_sum += loss.item() * len(idx)
            correct += (logits.argmax(1) == yb).sum().item()
        tr_acc = correct / len(Xtr)
        te_acc = evaluate(model, Xte, yte, a.batch, device)
        print(f"{e:5d}  {loss_sum/len(Xtr):.3f}  {tr_acc:9.4f}  {te_acc:.4f}  {time.time()-t0:5.1f}")
        if csv:
            csv.write(f"{e},{loss_sum/len(Xtr):.5f},{tr_acc:.5f},{te_acc:.5f}\n")
    if csv:
        csv.close()
        print(f"wrote {a.log_csv}")


if __name__ == "__main__":
    main()
